server:
  port: 8100
spring:
  application:
    name: product-stock-service
  datasource:
    url: jdbc:mysql://localhost:3307/pr_stock      
    username: admin_
    password: 3A397281@a
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format-sql: true    
